#!/usr/bin/env bun

import { exec } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";
import type { RegistryItem } from "shadcn/schema";
import { fixImport, getFileTarget } from "@/lib/registry";
import { registry } from "@/registry";

async function buildRegistryIndex() {
  let index = `
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react" 

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles =
      item.files?.map(
        (file: (typeof item.files)[number]) =>
          `src/registry/default/${file.path}`
      ) ?? [];
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/default/${item.files[0].path}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file: (typeof item.files)[number]) => {
      const filePath = `src/registry/default/${typeof file === "string" ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  rimraf.sync(path.join(process.cwd(), "src/registry/__index__.tsx"));
  await fs.writeFile(
    path.join(process.cwd(), "src/registry/__index__.tsx"),
    index
  );
}

async function buildRegistryJsonFile() {
  const fixedRegistry = {
    ...registry,
    items: await Promise.all(
      registry.items.map(async (item: RegistryItem) => {
        const files = await Promise.all(
          (item.files || []).map(async (file) => {
            const filePath = `src/registry/default/${file.path}`;
            const resolvedPath = path.isAbsolute(filePath)
              ? filePath
              : path.join(process.cwd(), filePath);

            let content: string | undefined;
            try {
              const rawContent = await fs.readFile(resolvedPath, "utf-8");
              content = fixImport(rawContent);
            } catch (error) {
              console.warn(
                `Warning: Could not read file ${resolvedPath}:`,
                error
              );
            }

            const target = getFileTarget({
              path: file.path,
              type: file.type,
              target: file.target,
            });

            return {
              ...file,
              path: filePath,
              target,
              ...(content !== undefined && { content }),
            };
          })
        );

        return {
          ...item,
          files,
        };
      })
    ),
  };

  rimraf.sync(path.join(process.cwd(), "registry.json"));
  await fs.writeFile(
    path.join(process.cwd(), "registry.json"),
    JSON.stringify(fixedRegistry, null, 2)
  );

  await fs.cp(
    path.join(process.cwd(), "registry.json"),
    path.join(process.cwd(), "public/r/registry.json"),
    { recursive: true }
  );
}

async function buildRegistry() {
  return await new Promise((resolve, reject) => {
    const process = exec("bunx shadcn build registry.json --output public/r");

    process.on("exit", (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log("🗂️ Building src/registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("💅 Building registry.json...");
  await buildRegistryJsonFile();

  console.log("🏗️ Building registry...");
  await buildRegistry();

  console.log("✅ Registry build completed successfully!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
