title: "[particles]: "
labels: ["Particles Request"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a particle request! Please search open/closed requests before submitting, as the particle or a similar one may have already been requested.

  - type: textarea
    id: particle-description
    attributes:
      label: Description
      description: Tell us about your particle request
      placeholder: "A dashboard for an e-commerce website showing sales, orders, and customers..."
    validations:
      required: true

  - type: input
    id: particle-example-url
    attributes:
      label: Example
      description: Link to an example of the particle
      placeholder: ex. https://example.com
    validations:
      required: false