
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react" 

export const Index: Record<string, any> = {
  "provider": {
    name: "provider",
    description: "",
    type: "registry:component",
    registryDependencies: ["@wallet-kit/context","@wallet-kit/network","@wallet-kit/storage","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/ui/wallet/provider.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/provider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "connect": {
    name: "connect",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/button","@shadcn/dialog","@shadcn/item","@shadcn/button-group","@wallet-kit/provider","@wallet-kit/list","@wallet-kit/onboarding","@wallet-kit/error","@wallet-kit/icon","@wallet-kit/ellipsify"],
    files: [{
      path: "src/registry/default/ui/wallet/connect.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/connect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "list": {
    name: "list",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/button","@shadcn/spinner","@shadcn/alert","@shadcn/badge","@wallet-kit/icon","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/ui/wallet/list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "menu": {
    name: "menu",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/button","@shadcn/dropdown-menu","@wallet-kit/connect","@wallet-kit/error","@wallet-kit/icon","@wallet-kit/ellipsify","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/ui/wallet/menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "network-control": {
    name: "network-control",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/badge","@wallet-kit/use-wallet","@wallet-kit/network"],
    files: [{
      path: "src/registry/default/ui/wallet/network.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/network.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "error": {
    name: "error",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/alert-dialog","@shadcn/button"],
    files: [{
      path: "src/registry/default/ui/wallet/error.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/error.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "onboarding": {
    name: "onboarding",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/button"],
    files: [{
      path: "src/registry/default/ui/wallet/onboarding.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/onboarding.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "icon": {
    name: "icon",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/avatar"],
    files: [{
      path: "src/registry/default/ui/wallet/icon.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "explorer-link": {
    name: "explorer-link",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/button","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/ui/wallet/explorer-link.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/explorer-link.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "balance": {
    name: "balance",
    description: "",
    type: "registry:component",
    registryDependencies: ["@shadcn/skeleton","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/ui/wallet/balance.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/wallet/balance.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "connect-wallet-demo": {
    name: "connect-wallet-demo",
    description: "A simple connect wallet button example",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/connect","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/connect-wallet-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/connect-wallet-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "connect-wallet-prompt-demo": {
    name: "connect-wallet-prompt-demo",
    description: "A prompt component that displays when no wallet is connected",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/connect","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/connect-wallet-prompt-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/connect-wallet-prompt-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "network-select-demo": {
    name: "network-select-demo",
    description: "Network selection control with badge and dropdown",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/network-control","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/network-select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/network-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-list-demo": {
    name: "wallet-list-demo",
    description: "List of available wallets with connect and disconnect actions",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/list","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-menu-demo": {
    name: "wallet-menu-demo",
    description: "Wallet dropdown menu with account info and actions",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/menu","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/wallet-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-error-demo": {
    name: "wallet-error-demo",
    description: "Wallet error dialog for displaying connection errors",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/error"],
    files: [{
      path: "src/registry/default/examples/wallet-error-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-error-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-onboarding-demo": {
    name: "wallet-onboarding-demo",
    description: "Interactive wallet onboarding flow with step-by-step guide",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/onboarding"],
    files: [{
      path: "src/registry/default/examples/wallet-onboarding-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-onboarding-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-icon-demo": {
    name: "wallet-icon-demo",
    description: "Wallet icon component with different size variants",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/icon","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-icon-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-balance-demo": {
    name: "wallet-balance-demo",
    description: "Display wallet balance with loading states and formatting",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/balance","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-balance-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-balance-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "solana-client-demo": {
    name: "solana-client-demo",
    description: "Example using SolanaWalletProvider and useSolanaWallet hook to interact with Solana RPC",
    type: "registry:example",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/solana-adapter","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/solana-client-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/solana-client-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "theme-stone": {
    name: "theme-stone",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-zinc": {
    name: "theme-zinc",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-neutral": {
    name: "theme-neutral",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-gray": {
    name: "theme-gray",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-slate": {
    name: "theme-slate",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "connect-wallet-demo": {
    name: "connect-wallet-demo",
    description: "A simple connect wallet button example",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/connect","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/connect-wallet-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/connect-wallet-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "connect-wallet-prompt-demo": {
    name: "connect-wallet-prompt-demo",
    description: "A prompt component that displays when no wallet is connected",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/connect","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/connect-wallet-prompt-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/connect-wallet-prompt-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-menu-demo": {
    name: "wallet-menu-demo",
    description: "Wallet dropdown menu with account info and actions",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/menu","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/wallet-menu-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "network-select-demo": {
    name: "network-select-demo",
    description: "Network selection control with badge and dropdown",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/network-control","@wallet-kit/solana"],
    files: [{
      path: "src/registry/default/examples/network-select-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/network-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-list-demo": {
    name: "wallet-list-demo",
    description: "List of available wallets with connect and disconnect actions",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/list","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-list-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-icon-demo": {
    name: "wallet-icon-demo",
    description: "Wallet icon component with different size variants",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/icon","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-icon-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-error-demo": {
    name: "wallet-error-demo",
    description: "Wallet error dialog for displaying connection errors",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/error"],
    files: [{
      path: "src/registry/default/examples/wallet-error-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-error-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-onboarding-demo": {
    name: "wallet-onboarding-demo",
    description: "Interactive wallet onboarding flow with step-by-step guide",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/onboarding"],
    files: [{
      path: "src/registry/default/examples/wallet-onboarding-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-onboarding-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "wallet-balance-demo": {
    name: "wallet-balance-demo",
    description: "Display wallet balance with loading states and formatting",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/balance","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/wallet-balance-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/wallet-balance-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "solana-client-demo": {
    name: "solana-client-demo",
    description: "Example using SolanaWalletProvider and useSolanaWallet hook to interact with Solana RPC",
    type: "registry:block",
    registryDependencies: ["@wallet-kit/provider","@wallet-kit/solana-adapter","@wallet-kit/solana","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/examples/solana-client-demo.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/solana-client-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["wallet"],
    meta: undefined,
  },
  "use-wallet": {
    name: "use-wallet",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@wallet-kit/context","@wallet-kit/network","@wallet-kit/storage"],
    files: [{
      path: "src/registry/default/hooks/use-wallet.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/hooks/use-wallet.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ellipsify": {
    name: "ellipsify",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/lib/ellipsify.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/ellipsify.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "network": {
    name: "network",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/lib/chains/network.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/chains/network.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "context": {
    name: "context",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/lib/chains/context.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/chains/context.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "storage": {
    name: "storage",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/lib/chains/storage.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/chains/storage.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "solana": {
    name: "solana",
    description: "",
    type: "registry:lib",
    registryDependencies: ["@wallet-kit/network"],
    files: [{
      path: "src/registry/default/lib/chains/solana/index.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/chains/solana/index.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "solana-adapter": {
    name: "solana-adapter",
    description: "",
    type: "registry:lib",
    registryDependencies: ["@wallet-kit/context","@wallet-kit/network","@wallet-kit/use-wallet"],
    files: [{
      path: "src/registry/default/lib/chains/solana/adapter.tsx",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/chains/solana/adapter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }